# Universal Windows Platform
# Build a Universal Windows Platform project using Visual Studio.
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  solution: 'UWPApp/UWPApp.sln'   # <-- Change if needed
  buildPlatform: 'x64'
  buildConfiguration: 'Release'
  appxPackageDir: '$(Build.ArtifactStagingDirectory)\AppxPackages\\'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '**\*.sln'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    msbuildArgs: >
      /p:AppxBundlePlatforms="$(buildPlatform)"
      /p:AppxPackageDir="$(appxPackageDir)"
      /p:AppxBundle=Always
      /p:UapAppxPackageBuildMode=StoreUpload"

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'AppxPackage'
